# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Tweet My River
                                 A QGIS plugin
 Tweet My River
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-16
        copyright            : (C) 2023 by Oliu Llorente / ICRA
        email                : ollorente@icra.cat
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Oliu Llorente / ICRA'
__date__ = '2023-02-16'
__copyright__ = '(C) 2023 by Oliu Llorente / ICRA'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Tweet_AI_classifier class from file Tweet_AI_classifier.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Tweer_AI_Classifier import Tweet_AI_classifierPlugin
    return Tweet_AI_classifierPlugin(iface)
